package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("тест вакансии 2")
    void generatedTest() {
        step("Открыть 'https://kazan.hh.ru/vacancy/55442983?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=qa'", () -> {
            step("// todo: just add selenium action");
        });

        step("Нажать 'Показать контакты'", () -> {
            step("// todo: just add selenium action");
        });

        step("Проверить контакты 'Чернявская Кристина", () -> {
            step("// todo: just add selenium action");
        });

        step("+7 (967) 1798887, TG @KristinaChernyavskaya", () -> {
            step("// todo: just add selenium action");
        });

        step("k.chernyavskaya@dltru.org'", () -> {
            step("// todo: just add selenium action");
        });

        step("Нажать 'Откликнуться'", () -> {
            step("// todo: just add selenium action");
        });

        step("проверить заголовок 'Дополнение резюме'", () -> {
            step("// todo: just add selenium action");
        });

        step("проверить заголовок 'Контактные данные'", () -> {
            step("// todo: just add selenium action");
        });

        step("ввести Мобильный телефон '+79998887755'", () -> {
            step("// todo: just add selenium action");
        });

        step("выбрать пол 'Женский'", () -> {
            step("// todo: just add selenium action");
        });

        step("нажать 'Откликнуться'", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://kazan.hh.ru/vacancy/55442983?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=qa'", () ->
            open("https://kazan.hh.ru/vacancy/55442983?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=qa"));

        step("Page title should have text 'Вакансия QA automation / AQA в Москве, работа в компании Системы Распределенного Реестра'", () -> {
            String expectedTitle = "Вакансия QA automation / AQA в Москве, работа в компании Системы Распределенного Реестра";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://kazan.hh.ru/vacancy/55442983?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=qa'", () ->
            open("https://kazan.hh.ru/vacancy/55442983?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=qa"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}